name: Deploy AWS SAM Backend

on:
  push:
    branches:
      - main  

jobs:
  test-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: 3.11

      - name: Install AWS SAM CLI
        run: |
          pip install aws-sam-cli

      - name: Install Dependencies
        run: |
          pip install -r hello_world/requirements.txt  

      - name: Run Tests
        run: |
          pytest test_visitor_counter.py 

      - name: Install Dependencies
        run: |
          pip install -r hello_world/requirements.txt  
      - name: Run Tests
        run: |
          pytest test_visitor_counter.py 
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1  

      - name: Deploy with AWS SAM
        run: |
          sam build
          sam deploy --no-confirm-changeset --no-fail-on-empty-changeset
          sam deploy --no-confirm-changeset --no-fail-on-empty-changeset
